//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMButtonState {
  PSMButtonState_UP = 0x00,
  PSMButtonState_PRESSED = 0x01,
  PSMButtonState_DOWN = 0x03,
  PSMButtonState_RELEASED = 0x02
}

}
