//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMBatteryState {
  PSMBattery_0 = 0,
  PSMBattery_20 = 1,
  PSMBattery_40 = 2,
  PSMBattery_60 = 3,
  PSMBattery_80 = 4,
  PSMBattery_100 = 5,
  PSMBattery_Charging = 0xEE,
  PSMBattery_Charged = 0xEF
}

}
