//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMController : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMController(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMController() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMController(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int ControllerID {
    get {
      int ret = PSMoveClientPINVOKE.PSMController_ControllerID_get(swigCPtr);
      return ret;
    } 
  }

  public PSMControllerType ControllerType {
    get {
      PSMControllerType ret = (PSMControllerType)PSMoveClientPINVOKE.PSMController_ControllerType_get(swigCPtr);
      return ret;
    } 
  }

  public PSMControllerHand ControllerHand {
    get {
      PSMControllerHand ret = (PSMControllerHand)PSMoveClientPINVOKE.PSMController_ControllerHand_get(swigCPtr);
      return ret;
    } 
  }

  public PSMController_ControllerState ControllerState {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMController_ControllerState_get(swigCPtr);
      PSMController_ControllerState ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMController_ControllerState(cPtr, false);
      return ret;
    } 
  }

  public bool bValid {
    get {
      bool ret = PSMoveClientPINVOKE.PSMController_bValid_get(swigCPtr);
      return ret;
    } 
  }

  public int OutputSequenceNum {
    get {
      int ret = PSMoveClientPINVOKE.PSMController_OutputSequenceNum_get(swigCPtr);
      return ret;
    } 
  }

  public int InputSequenceNum {
    get {
      int ret = PSMoveClientPINVOKE.PSMController_InputSequenceNum_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsConnected {
    get {
      bool ret = PSMoveClientPINVOKE.PSMController_IsConnected_get(swigCPtr);
      return ret;
    } 
  }

  public long DataFrameLastReceivedTime {
    get {
      long ret = PSMoveClientPINVOKE.PSMController_DataFrameLastReceivedTime_get(swigCPtr);
      return ret;
    } 
  }

  public float DataFrameAverageFPS {
    get {
      float ret = PSMoveClientPINVOKE.PSMController_DataFrameAverageFPS_get(swigCPtr);
      return ret;
    } 
  }

  public int ListenerCount {
    get {
      int ret = PSMoveClientPINVOKE.PSMController_ListenerCount_get(swigCPtr);
      return ret;
    } 
  }

  public PSMController() : this(PSMoveClientPINVOKE.new_PSMController(), true) {
  }

}

}
