//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMController_ControllerState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMController_ControllerState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMController_ControllerState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMController_ControllerState() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMController_ControllerState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMPSMove PSMoveState {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMController_ControllerState_PSMoveState_get(swigCPtr);
      PSMPSMove ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPSMove(cPtr, false);
      return ret;
    } 
  }

  public PSMPSNavi PSNaviState {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMController_ControllerState_PSNaviState_get(swigCPtr);
      PSMPSNavi ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPSNavi(cPtr, false);
      return ret;
    } 
  }

  public PSMDualShock4 PSDS4State {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMController_ControllerState_PSDS4State_get(swigCPtr);
      PSMDualShock4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMDualShock4(cPtr, false);
      return ret;
    } 
  }

  public PSMVirtualController VirtualController {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMController_ControllerState_VirtualController_get(swigCPtr);
      PSMVirtualController ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVirtualController(cPtr, false);
      return ret;
    } 
  }

  public PSMController_ControllerState() : this(PSMoveClientPINVOKE.new_PSMController_ControllerState(), true) {
  }

}

}
