//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMControllerDataStreamFlags {
  PSMStreamFlags_defaultStreamOptions = 0x00,
  PSMStreamFlags_includePositionData = 0x01,
  PSMStreamFlags_includePhysicsData = 0x02,
  PSMStreamFlags_includeRawSensorData = 0x04,
  PSMStreamFlags_includeCalibratedSensorData = 0x08,
  PSMStreamFlags_includeRawTrackerData = 0x10,
  PSMStreamFlags_disableROI = 0x20
}

}
