//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMEventMessageType {
  PSMEvent_connectedToService,
  PSMEvent_failedToConnectToService,
  PSMEvent_disconnectedFromService,
  PSMEvent_opaqueServiceEvent,
  PSMEvent_controllerListUpdated,
  PSMEvent_trackerListUpdated,
  PSMEvent_hmdListUpdated,
  PSMEvent_systemButtonPressed
}

}
