//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMHmdList : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMHmdList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMHmdList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMHmdList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMHmdList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMClientHMDInfo[] hmds {
    get {
      PSMClientHMDInfo[] returnArray;
      
      int structSize = (int)PSMoveClientPINVOKE.PSMClientHMDInfo_getSize();
      System.IntPtr cPtr = PSMoveClientPINVOKE.PSMHmdList_hmds_get(swigCPtr);
      int len = this.count;
      if (len<=0)
      {
        return null;
      }
      returnArray = new PSMClientHMDInfo[len];
      for (int i = 0; i < len; ++i)
      {
          System.IntPtr data = new System.IntPtr(cPtr.ToInt64() + structSize * i);
          returnArray[i] = new PSMClientHMDInfo(data, false);        
      }

      return returnArray;
    }
  
  }

  public int count {
    get {
      int ret = PSMoveClientPINVOKE.PSMHmdList_count_get(swigCPtr);
      return ret;
    } 
  }

  public PSMHmdList() : this(PSMoveClientPINVOKE.new_PSMHmdList(), true) {
  }

}

}
