//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMMorpheus : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMMorpheus(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMMorpheus obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMMorpheus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMMorpheus(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool bIsTrackingEnabled {
    get {
      bool ret = PSMoveClientPINVOKE.PSMMorpheus_bIsTrackingEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public bool bIsCurrentlyTracking {
    get {
      bool ret = PSMoveClientPINVOKE.PSMMorpheus_bIsCurrentlyTracking_get(swigCPtr);
      return ret;
    } 
  }

  public bool bIsOrientationValid {
    get {
      bool ret = PSMoveClientPINVOKE.PSMMorpheus_bIsOrientationValid_get(swigCPtr);
      return ret;
    } 
  }

  public bool bIsPositionValid {
    get {
      bool ret = PSMoveClientPINVOKE.PSMMorpheus_bIsPositionValid_get(swigCPtr);
      return ret;
    } 
  }

  public PSMPosef Pose {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMorpheus_Pose_get(swigCPtr);
      PSMPosef ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPosef(cPtr, false);
      return ret;
    } 
  }

  public PSMPhysicsData PhysicsData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMorpheus_PhysicsData_get(swigCPtr);
      PSMPhysicsData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPhysicsData(cPtr, false);
      return ret;
    } 
  }

  public PSMMorpheusRawSensorData RawSensorData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMorpheus_RawSensorData_get(swigCPtr);
      PSMMorpheusRawSensorData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMMorpheusRawSensorData(cPtr, false);
      return ret;
    } 
  }

  public PSMMorpheusCalibratedSensorData CalibratedSensorData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMorpheus_CalibratedSensorData_get(swigCPtr);
      PSMMorpheusCalibratedSensorData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMMorpheusCalibratedSensorData(cPtr, false);
      return ret;
    } 
  }

  public PSMRawTrackerData RawTrackerData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMorpheus_RawTrackerData_get(swigCPtr);
      PSMRawTrackerData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMRawTrackerData(cPtr, false);
      return ret;
    } 
  }

  public PSMMorpheus() : this(PSMoveClientPINVOKE.new_PSMMorpheus(), true) {
  }

}

}
