//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMMatrix3f : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMMatrix3f(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMMatrix3f obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMMatrix3f() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMMatrix3f(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float m00 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m00_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m00_get(swigCPtr);
      return ret;
    } 
  }

  public float m01 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m01_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m01_get(swigCPtr);
      return ret;
    } 
  }

  public float m02 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m02_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m02_get(swigCPtr);
      return ret;
    } 
  }

  public float m10 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m10_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m10_get(swigCPtr);
      return ret;
    } 
  }

  public float m11 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m11_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m11_get(swigCPtr);
      return ret;
    } 
  }

  public float m12 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m12_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m12_get(swigCPtr);
      return ret;
    } 
  }

  public float m20 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m20_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m20_get(swigCPtr);
      return ret;
    } 
  }

  public float m21 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m21_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m21_get(swigCPtr);
      return ret;
    } 
  }

  public float m22 {
    set {
      PSMoveClientPINVOKE.PSMMatrix3f_m22_set(swigCPtr, value);
    } 
    get {
      float ret = PSMoveClientPINVOKE.PSMMatrix3f_m22_get(swigCPtr);
      return ret;
    } 
  }

  public PSMMatrix3f() : this(PSMoveClientPINVOKE.new_PSMMatrix3f(), true) {
  }

}

}
