//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMMessage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMMessage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMEventMessage event_data {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMessage_event_data_get(swigCPtr);
      PSMEventMessage ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMEventMessage(cPtr, false);
      return ret;
    } 
  }

  public PSMResponseMessage response_data {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMMessage_response_data_get(swigCPtr);
      PSMResponseMessage ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMResponseMessage(cPtr, false);
      return ret;
    } 
  }

  public PSMMessageType payload_type {
    get {
      PSMMessageType ret = (PSMMessageType)PSMoveClientPINVOKE.PSMMessage_payload_type_get(swigCPtr);
      return ret;
    } 
  }

  public PSMMessage() : this(PSMoveClientPINVOKE.new_PSMMessage(), true) {
  }

}

}
