//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMPhysicsData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMPhysicsData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMPhysicsData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMPhysicsData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMPhysicsData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMVector3f LinearVelocityCmPerSec {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMPhysicsData_LinearVelocityCmPerSec_get(swigCPtr);
      PSMVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVector3f(cPtr, false);
      return ret;
    } 
  }

  public PSMVector3f LinearAccelerationCmPerSecSqr {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMPhysicsData_LinearAccelerationCmPerSecSqr_get(swigCPtr);
      PSMVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVector3f(cPtr, false);
      return ret;
    } 
  }

  public PSMVector3f AngularVelocityRadPerSec {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMPhysicsData_AngularVelocityRadPerSec_get(swigCPtr);
      PSMVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVector3f(cPtr, false);
      return ret;
    } 
  }

  public PSMVector3f AngularAccelerationRadPerSecSqr {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMPhysicsData_AngularAccelerationRadPerSecSqr_get(swigCPtr);
      PSMVector3f ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVector3f(cPtr, false);
      return ret;
    } 
  }

  public double TimeInSeconds {
    get {
      double ret = PSMoveClientPINVOKE.PSMPhysicsData_TimeInSeconds_get(swigCPtr);
      return ret;
    } 
  }

  public PSMPhysicsData() : this(PSMoveClientPINVOKE.new_PSMPhysicsData(), true) {
  }

}

}
