//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMResponsePayloadType {
  _responsePayloadType_Empty,
  _responsePayloadType_ServiceVersion,
  _responsePayloadType_ControllerList,
  _responsePayloadType_TrackerList,
  _responsePayloadType_TrackingSpace,
  _responsePayloadType_HmdList,
  _responsePayloadType_Count
}

}
