//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMResponseMessage_payload : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMResponseMessage_payload(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMResponseMessage_payload obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMResponseMessage_payload() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMResponseMessage_payload(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMServiceVersion service_version {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_service_version_get(swigCPtr);
      PSMServiceVersion ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMServiceVersion(cPtr, false);
      return ret;
    } 
  }

  public PSMControllerList controller_list {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_controller_list_get(swigCPtr);
      PSMControllerList ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMControllerList(cPtr, false);
      return ret;
    } 
  }

  public PSMTrackerList tracker_list {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_tracker_list_get(swigCPtr);
      PSMTrackerList ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMTrackerList(cPtr, false);
      return ret;
    } 
  }

  public PSMHmdList hmd_list {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_hmd_list_get(swigCPtr);
      PSMHmdList ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMHmdList(cPtr, false);
      return ret;
    } 
  }

  public PSMTrackingSpace tracking_space {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_tracking_space_get(swigCPtr);
      PSMTrackingSpace ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMTrackingSpace(cPtr, false);
      return ret;
    } 
  }

  public PSMResponseMessage_payload() : this(PSMoveClientPINVOKE.new_PSMResponseMessage_payload(), true) {
  }

}

}
