//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMResponseMessage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMResponseMessage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMResponseMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMResponseMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMResponseMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int request_id {
    get {
      int ret = PSMoveClientPINVOKE.PSMResponseMessage_request_id_get(swigCPtr);
      return ret;
    } 
  }

  public PSMResult result_code {
    get {
      PSMResult ret = (PSMResult)PSMoveClientPINVOKE.PSMResponseMessage_result_code_get(swigCPtr);
      return ret;
    } 
  }

  public System.IntPtr opaque_request_handle { 
    get {
        System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_opaque_request_handle_get(swigCPtr); 
        return cPtr; 
   } 

  }

  public System.IntPtr opaque_response_handle { 
    get {
        System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_opaque_response_handle_get(swigCPtr); 
        return cPtr; 
   } 

  }

  public PSMResponseMessage_payload payload {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMResponseMessage_payload_get(swigCPtr);
      PSMResponseMessage_payload ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMResponseMessage_payload(cPtr, false);
      return ret;
    } 
  }

  public PSMResponsePayloadType payload_type {
    get {
      PSMResponsePayloadType ret = (PSMResponsePayloadType)PSMoveClientPINVOKE.PSMResponseMessage_payload_type_get(swigCPtr);
      return ret;
    } 
  }

  public PSMResponseMessage() : this(PSMoveClientPINVOKE.new_PSMResponseMessage(), true) {
  }

}

}
