//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMTrackingProjection_shape_ellipse : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMTrackingProjection_shape_ellipse(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMTrackingProjection_shape_ellipse obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMTrackingProjection_shape_ellipse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMTrackingProjection_shape_ellipse(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMVector2f center {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMTrackingProjection_shape_ellipse_center_get(swigCPtr);
      PSMVector2f ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMVector2f(cPtr, false);
      return ret;
    } 
  }

  public float half_x_extent {
    get {
      float ret = PSMoveClientPINVOKE.PSMTrackingProjection_shape_ellipse_half_x_extent_get(swigCPtr);
      return ret;
    } 
  }

  public float half_y_extent {
    get {
      float ret = PSMoveClientPINVOKE.PSMTrackingProjection_shape_ellipse_half_y_extent_get(swigCPtr);
      return ret;
    } 
  }

  public float angle {
    get {
      float ret = PSMoveClientPINVOKE.PSMTrackingProjection_shape_ellipse_angle_get(swigCPtr);
      return ret;
    } 
  }

  public PSMTrackingProjection_shape_ellipse() : this(PSMoveClientPINVOKE.new_PSMTrackingProjection_shape_ellipse(), true) {
  }

}

}
