//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMTrackingColorType {
  PSMTrackingColorType_Magenta,
  PSMTrackingColorType_Cyan,
  PSMTrackingColorType_Yellow,
  PSMTrackingColorType_Red,
  PSMTrackingColorType_Green,
  PSMTrackingColorType_Blue,
  PSMTrackingColorType_MaxColorTypes
}

}
