//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMTracker : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMTracker(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMTracker obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMTracker() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMTracker(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMClientTrackerInfo tracker_info {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMTracker_tracker_info_get(swigCPtr);
      PSMClientTrackerInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMClientTrackerInfo(cPtr, false);
      return ret;
    } 
  }

  public int listener_count {
    get {
      int ret = PSMoveClientPINVOKE.PSMTracker_listener_count_get(swigCPtr);
      return ret;
    } 
  }

  public bool is_connected {
    get {
      bool ret = PSMoveClientPINVOKE.PSMTracker_is_connected_get(swigCPtr);
      return ret;
    } 
  }

  public int sequence_num {
    get {
      int ret = PSMoveClientPINVOKE.PSMTracker_sequence_num_get(swigCPtr);
      return ret;
    } 
  }

  public long data_frame_last_received_time {
    get {
      long ret = PSMoveClientPINVOKE.PSMTracker_data_frame_last_received_time_get(swigCPtr);
      return ret;
    } 
  }

  public float data_frame_average_fps {
    get {
      float ret = PSMoveClientPINVOKE.PSMTracker_data_frame_average_fps_get(swigCPtr);
      return ret;
    } 
  }

  public System.IntPtr opaque_shared_memory_accesor { 
    get {
        System.IntPtr cPtr = PSMoveClientPINVOKE.PSMTracker_opaque_shared_memory_accesor_get(swigCPtr); 
        return cPtr; 
   } 

  }

  public PSMTracker() : this(PSMoveClientPINVOKE.new_PSMTracker(), true) {
  }

}

}
