//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMTrackingProjection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMTrackingProjection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMTrackingProjection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMTrackingProjection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMTrackingProjection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMTrackingShapeType shape_type {
    get {
      PSMTrackingShapeType ret = (PSMTrackingShapeType)PSMoveClientPINVOKE.PSMTrackingProjection_shape_type_get(swigCPtr);
      return ret;
    } 
  }

  public PSMTrackingProjection_shape shape {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMTrackingProjection_shape_get(swigCPtr);
      PSMTrackingProjection_shape ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMTrackingProjection_shape(cPtr, false);
      return ret;
    } 
  }

  public PSMTrackingProjection() : this(PSMoveClientPINVOKE.new_PSMTrackingProjection(), true) {
  }

}

}
