//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public enum PSMTrackingShapeType {
  PSMShape_INVALID_PROJECTION = -1,
  PSMShape_Ellipse,
  PSMShape_LightBar,
  PSMShape_PointCloud
}

}
