//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PSMoveService {

public class PSMVirtualHMD : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMVirtualHMD(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMVirtualHMD obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMVirtualHMD() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PSMoveClientPINVOKE.delete_PSMVirtualHMD(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool bIsTrackingEnabled {
    get {
      bool ret = PSMoveClientPINVOKE.PSMVirtualHMD_bIsTrackingEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public bool bIsCurrentlyTracking {
    get {
      bool ret = PSMoveClientPINVOKE.PSMVirtualHMD_bIsCurrentlyTracking_get(swigCPtr);
      return ret;
    } 
  }

  public bool bIsPositionValid {
    get {
      bool ret = PSMoveClientPINVOKE.PSMVirtualHMD_bIsPositionValid_get(swigCPtr);
      return ret;
    } 
  }

  public PSMPosef Pose {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMVirtualHMD_Pose_get(swigCPtr);
      PSMPosef ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPosef(cPtr, false);
      return ret;
    } 
  }

  public PSMPhysicsData PhysicsData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMVirtualHMD_PhysicsData_get(swigCPtr);
      PSMPhysicsData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMPhysicsData(cPtr, false);
      return ret;
    } 
  }

  public PSMRawTrackerData RawTrackerData {
    get {
      global::System.IntPtr cPtr = PSMoveClientPINVOKE.PSMVirtualHMD_RawTrackerData_get(swigCPtr);
      PSMRawTrackerData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMRawTrackerData(cPtr, false);
      return ret;
    } 
  }

  public PSMVirtualHMD() : this(PSMoveClientPINVOKE.new_PSMVirtualHMD(), true) {
  }

}

}
